version: '3.8'

services:
  tuvalu-forecast:
    build:
      context: .
      dockerfile: Dockerfile
    image: tuvalu-forecast:latest
    container_name: tuvalu-forecast
    volumes:
      - ./runs:/TuvaluForecast/runs
      - ./logs:/TuvaluForecast/logs
      - ./tmp:/TuvaluForecast/tmp
      - ./archives:/TuvaluForecast/archives
      - ./Regional_Output:/TuvaluForecast/Regional_Output
      - ./.copernicusmarine:/root/.copernicusmarine
      - ./.env:/TuvaluForecast/.env
    environment:
      - PYTHONPATH=/TuvaluForecast/codes:/TuvaluForecast/common
    working_dir: /TuvaluForecast/codes
    stdin_open: true
    tty: true
